pacientes/urls.py
from django.urls import path

from .views import PacienteListView
from .views import PacienteCreateView
from .views import PacienteUpdateView
from .views import PacienteDeleteView
from .views import PacienteDetailView
from .views import PacienteListAjaxView
from .views import PacienteCreateAjaxView

app_name = 'pacientes'

urlpatterns = [
    path('', PacienteListView.as_view(), name="paciente_list"),
    path('adicionar/', PacienteCreateView.as_view(), name="paciente_add"),
    path('adicionar/ajax/', PacienteCreateAjaxView.as_view(),
         name="paciente_add_ajax"),
    path('buscar_pacientes/', PacienteListAjaxView.as_view(),
         name="paciente_buscar"),
    path('<int:pk>/editar/', PacienteUpdateView.as_view(),
         name="paciente_edit"),
    path('<int:pk>/excluir/', PacienteDeleteView.as_view(),
         name="paciente_delete"),
    path('<int:pk>/detalhes/', PacienteDetailView.as_view(),
         name="paciente_detail"),
]

siga/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from siga.views import Index


urlpatterns = [
    path('pacientes/', include('pacientes.urls')),
    path('estetica/', include('procedimentos.urls')),
    path('financeiro/', include('movimentacoes.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('', Index.as_view(), name='home')
]

pacientes/models.py
from django.db import models


class Paciente(models.Model):
    nome = models.CharField(max_length=200)
    data_nascimento = models.DateField("Nascimento", null=True, blank=True)
    cpf = models.CharField("CPF", max_length=14, null=True, blank=True)
    rg = models.CharField("RG", max_length=50, null=True, blank=True)
    telefone = models.CharField(max_length=20)
    endereco = models.CharField(
        "Endereço", max_length=200, null=True, blank=True)
    cidade = models.CharField(max_length=200, null=True, blank=True)
    estado = models.CharField(
        max_length=200, default="PI", null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    profissao = models.CharField(
        "Profissão", max_length=200, null=True, blank=True)

    def __str__(self):
        return self.nome

pacientes/forms.py
from django import forms

from .models import Paciente


class PacienteForm(forms.ModelForm):
    """Form definition for Paciente."""

    class Meta:
        """Meta definition for Pacienteform."""

        model = Paciente
        fields = ('nome',
                  'data_nascimento',
                  'cpf',
                  'rg',
                  'telefone',
                  'endereco',
                  'cidade',
                  'estado',
                  'email',
                  'profissao',)

        widgets = {
            'nome': forms.TextInput(
                attrs={'class': 'form-control border-info'}),
            'data_nascimento': forms.DateInput(
                attrs={
                    'class': 'form-control border-info',
                    'data-inputmask': '\'mask\': \'99/99/9999\'',
                    'im-insert': 'true'}),
            'cpf': forms.TextInput(
                attrs={
                    'class': 'form-control border-info',
                    'data-inputmask': '\'mask\': \'999.999.999-99\'',
                    'im-insert': 'true'}),
            'rg': forms.TextInput(
                attrs={'class': 'form-control border-info'}),
            'telefone': forms.TextInput(
                attrs={
                    'class': 'form-control border-info',
                    'data-inputmask': '\'mask\': \'(99) 99999-9999\'',
                    'im-insert': 'true'}),
            'endereco': forms.TextInput(
                attrs={'class': 'form-control border-info'}),
            'cidade': forms.TextInput(
                attrs={'class': 'form-control border-info'}),
            'estado': forms.TextInput(
                attrs={'class': 'form-control border-info'}),
            'email': forms.EmailInput(
                attrs={'class': 'form-control border-info'}),
            'profissao': forms.TextInput(
                attrs={'class': 'form-control border-info'}),
        }

pacientes/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.forms.models import model_to_dict

from pacientes.models import Paciente
from pacientes.forms import PacienteForm


class PacienteListView(\
    LoginRequiredMixin, PermissionRequiredMixin, ListView):  # pylint: disable=too-many-ancestors
    """Lista de Pacientes"""
    model = Paciente
    template_name = 'pacientes/list.html'
    permission_required = "pacientes.view_paciente"
    login_url = reverse_lazy('admin:login')


class PacienteCreateView(\
    LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Paciente
    template_name = "pacientes/form.html"
    form_class = PacienteForm
    success_url = reverse_lazy('pacientes:paciente_list')
    permission_required = "pacientes.add_paciente"
    login_url = reverse_lazy('admin:login')


class PacienteUpdateView(\
    LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Paciente
    template_name = "pacientes/form.html"
    form_class = PacienteForm
    success_url = reverse_lazy('pacientes:paciente_list')
    permission_required = "pacientes.change_paciente"
    login_url = reverse_lazy('admin:login')


class PacienteDeleteView(\
    LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Paciente
    success_url = reverse_lazy('pacientes:paciente_list')
    permission_required = "pacientes.delete_paciente"
    login_url = reverse_lazy('admin:login')



class PacienteDetailView(\
    LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Paciente
    template_name = "pacientes/detail.html"
    permission_required = "pacientes.view_paciente"
    login_url = reverse_lazy('admin:login')


class PacienteListAjaxView(\
    LoginRequiredMixin, PermissionRequiredMixin, View):

    permission_required = "pacientes.view_paciente"
    login_url = reverse_lazy('admin:login')

    def get(self, request):
        pacientes = serializers.serialize('json',
                                          Paciente.objects.all()
                                          .order_by('nome'),
                                          fields=('id', 'nome', 'telefone',))
        return HttpResponse(pacientes, content_type="application/json")


class PacienteCreateAjaxView(\
    LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = "pacientes.add_paciente"
    login_url = reverse_lazy('admin:login')

    def post(self, request):
        nome = request.POST.get('nome', '')
        telefone = request.POST.get('telefone', '')
        paciente = Paciente(nome=nome, telefone=telefone)
        paciente.save()
        return JsonResponse(model_to_dict(paciente), status=200)

pacientes/templates/pacientes/detail.html
{% extends 'base.html' %}
{% load static %}


{% block css %}


{% endblock css %}


{% block nav_inicio %}

<li>

{% endblock nav_inicio %}


{% block nav_pacientes %}

<li class="active open">

{% endblock nav_pacientes %}


{% block nav_pacientes_listagem %}

<li class="active">

{% endblock nav_pacientes_listagem %}


{% block breadcrumb-item %}

<li class="breadcrumb-item activate"><a href="{% url 'pacientes:paciente_list' %}">Pacientes</a></li>
<li class="breadcrumb-item activate"><a href="{% url 'pacientes:paciente_list' %}">Listagem</a></li>
<li class="breadcrumb-item activate">Informações</li>

{% endblock breadcrumb-item %}


{% block subheader_title %}

<i class='subheader-icon fal fa-address-card'></i> Pacientes: <span class="fw-300">Informações</span>

{% endblock subheader_title %}

{% block subheader_subtitle %}

Perfil e Agendamentos

{% endblock subheader_subtitle %}


{% block subheader_block %}


{% endblock subheader_block %}


{% block content %}
<div class="row">
    <div class="col">
        <a href="javascript:void(0)" class="btn btn-success btn-block font-weight-bold fs-xl">
           <i class="fas fa-address-book"></i> 
           <span class="hidden-md-down ml-1"> Agendar Atendimento</span>
        </a>
    </div>
    <div class="col">
        <a href="{% url 'pacientes:paciente_edit' object.id %}" class="btn btn-primary btn-block font-weight-bold fs-xl">
            <i class="fas fa-edit"></i> 
            <span class="hidden-md-down ml-1"> Alterar Dados Pessoais</span>
        </a>
    </div>
    <div class="col">
        <a href="javascript:void(0)" id="btn_excluir" class="btn btn-danger btn-block font-weight-bold fs-xl" rel="{{ object.nome }}">
            <i class="fas fa-times"></i> 
            <span class="hidden-md-down ml-1"> Excluir Paciente</span>
        </a>
    </div>
</div>
<div class="row">&nbsp;</div>
<div class="row">
    <div class="col-xl-12">
        <div id="panel-1" class="panel">
            <div class="panel-hdr">
                <h2>
                    Informações de <span class="fw-300"><i>{{ object.nome }}</i></span>
                </h2>
            </div>
            <div class="panel-container show">
                <div class="panel-content">
                    <div class="row">
                        <div class="col-auto">
                            <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                                <a class="nav-link active" id="v-pills-perfil-tab" data-toggle="pill" href="#v-pills-perfil" role="tab"
                                    aria-controls="v-pills-perfil" aria-selected="false">
                                    <i class="fal fa-user"></i>
                                    <span class="hidden-sm-down ml-1"> Perfil</span>
                                </a>
                                <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab"
                                    aria-controls="v-pills-messages" aria-selected="false">
                                    <i class="fal fa-envelope"></i>
                                    <span class="hidden-sm-down ml-1"> Messages</span>
                                </a>
                                <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab"
                                    aria-controls="v-pills-settings" aria-selected="false">
                                    <i class="fal fa-cog"></i>
                                    <span class="hidden-sm-down ml-1"> Settings</span>
                                </a>
                            </div>
                        </div>
                        <div class="col">
                            <div class="tab-content" id="v-pills-tabContent">
                                <div class="tab-pane fade show active" id="v-pills-perfil" role="tabpanel" aria-labelledby="v-pills-perfil-tab">
                                    <h1>
                                        Perfil
                                    </h1>
                                    <hr>
                                    <div class="d-flex flex-row rounded-top mb-3">
                                        <div>
                                            <dl class="row">
                                                <dt class="col-sm-3 fs-xl">Nome</dt>
                                                <dd class="col-sm-9 fs-xl">{{ object.nome }}</dd>
                                                <dt class="col-sm-3 fs-xl">Telefone</dt>
                                                <dd class="col-sm-9 fs-xl">
                                                    <a href="tel:{{ object.telefone }}">
                                                        {{ object.telefone }}
                                                    </a>
                                                </dd>
                                                
                                                {% if object.data_nascimento %}
                                                    <dt class="col-sm-3 fs-xl">Nascimento</dt>
                                                    <dd class="col-sm-9 fs-xl">
                                                        {{ object.data_nascimento }}
                                                    </dd>
                                                {% endif %}
                                                {% if object.cpf %}
                                                    <dt class="col-sm-3 fs-xl">CPF</dt>
                                                    <dd class="col-sm-9 fs-xl">{{ object.cpf }}</dd>
                                                {% endif %}
                                                {% if object.rg %}
                                                    <dt class="col-sm-3 fs-xl">RG</dt>
                                                    <dd class="col-sm-9 fs-xl">{{ object.rg }}</dd>
                                                {% endif %}
                                                {% if object.endereco or object.cidade or object.estado %}
                                                    <dt class="col-sm-3 fs-xl">Endereço</dt>
                                                    <dd class="col-sm-9 fs-xl">
                                                        {% if object.endereco %}
                                                            {{ object.endereco }},
                                                        {% endif %}
                                                            
                                                        {% if object.cidade %}
                                                            {{ object.cidade }} - 
                                                        {% endif %}
                                                        
                                                        {% if object.estado %}
                                                            {{ object.estado }}
                                                        {% endif %}
                                                    </dd>
                                                {% endif %}
                                                {% if object.email %}
                                                    <dt class="col-sm-3 fs-xl">Email</dt>
                                                    <dd class="col-sm-9 fs-xl">{{ object.email }}</dd>
                                                {% endif %}
                                                {% if object.profissao %}
                                                    <dt class="col-sm-3 fs-xl">Profissão</dt>
                                                    <dd class="col-sm-9 fs-xl">{{ object.profissao }}</dd>
                                                {% endif %}
                                            </dl>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
                                    <h3>
                                        Messages
                                    </h3>
                                    <ul class="notification">
                                        <li>
                                            <a href="#" class="d-flex align-items-center py-2 px-0">
                                                <span class="d-flex flex-column flex-1">
                                                    <span class="name">Melissa Ayre</span>
                                                    <span class="msg-a fs-sm">Re: New security codes</span>
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" class="d-flex align-items-center py-2 px-0">
                                                <span class="d-flex flex-column flex-1">
                                                    <span class="name">Adison Lee</span>
                                                    <span class="msg-a fs-sm">Msed quia non numquam eius</span>
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" class="d-flex align-items-center py-2 px-0">
                                                <span class="d-flex flex-column flex-1">
                                                    <span class="name">Oliver Kopyuv</span>
                                                    <span class="msg-a fs-sm">Msed quia non numquam eius</span>
                                                </span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
                                    <h3>Settings</h3>
                                    <div class="alert alert-success">
                                        <strong>
                                            Settings saved
                                        </strong>
                                        <p class="m-0">
                                            All your settings changes have been saved!
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<form id="excluir" action="{% url 'pacientes:paciente_delete' object.id %}" method="POST">{% csrf_token %}</form>
{% endblock content %}


{% block javascript %}
<script>
    $(document).ready(function(){
        $("#btn_excluir").click(function(e){
            var nome = $(this).attr('rel');
            bootbox.confirm(
            {
                message: "Tem certeza que deseja excluir todos os dados do paciente <strong>" + nome + "</strong>?",
                buttons:
                {
                    cancel:
                    {
                        label: 'Não',
                        className: 'btn-danger'
                    },
                    confirm:
                    {
                        label: 'Sim',
                        className: 'btn-success'
                    }
                },
                callback: function(result)
                {
                    if (result){
                        $('#excluir').submit();
                    }
                }
            });
        });
    });
</script>
{% endblock javascript %}

pacientes/templates/pacientes/form.html
{% extends 'base.html' %}
{% load static %}


{% block css %}

{% endblock css %}


{% block nav_inicio %}

    <li>

{% endblock nav_inicio %}


{% block nav_pacientes %}

    <li class="active open">
    
{% endblock nav_pacientes %}


{% block nav_pacientes_cadastrar %}

<li class="active">

{% endblock nav_pacientes_cadastrar %}


{% block breadcrumb-item %}

<li class="breadcrumb-item activate"><a href="{% url 'pacientes:paciente_list' %}">Pacientes</a></li>

{% if object.id %}

<li class="breadcrumb-item activate"><a href="{% url 'pacientes:paciente_list' %}">Listagem</a></li>
<li class="breadcrumb-item activate">Editar</li>

{% else %}

<li class="breadcrumb-item activate">Cadastro</li>

{% endif %}

{% endblock breadcrumb-item %}


{% block subheader_title %}

<i class='subheader-icon fal fa-address-card'></i> Pacientes: <span class="fw-300">Cadastro</span>

{% endblock subheader_title %}

{% block subheader_subtitle %}

Fórmulário de Cadastro

{% endblock subheader_subtitle %}


{% block subheader_block %}

{% endblock subheader_block %}


{% block content %}

<div class="row">
    <div class="col-xl-12">
        <div id="panel-1" class="panel">
            <div class="panel-hdr">
                <h2>

                    {% if object %}
                        Editar cadastro de <span class="fw-300">{{ object.nome }}</span>
                    {% else %}
                        Cadastrar Paciente
                    {% endif %}
                        
                </h2>
            </div>
            <div class="panel-container show">
                
                {% if object %}
                    <form action="{% url 'pacientes:paciente_edit' object.id %}" method="POST">
                {% else %}
                    <form action="{% url 'pacientes:paciente_add' %}" method="POST">
                {% endif %}
                    {% csrf_token %}
                    <div class="panel-content">
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label class="form-label" for="nome">Nome</label>
                                    {{ form.nome }}
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label class="form-label" for="nome">Telefone</label>
                                    {{ form.telefone }}
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <label class="form-label" for="nome">Nascimento</label>
                                    {{ form.data_nascimento }}
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label class="form-label" for="nome">CPF</label>
                                    {{ form.cpf }}
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <label class="form-label" for="nome">RG</label>
                                    {{ form.rg }}
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label class="form-label" for="nome">Endereço</label>
                                    {{ form.endereco }}
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label class="form-label" for="nome">Cidade</label>
                                    {{ form.cidade }}
                                </div>
                            </div>
                            
                            <div class="col">
                                <div class="form-group">
                                    <label class="form-label" for="nome">UF</label>
                                    {{ form.estado }}
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label class="form-label" for="nome">Email</label>
                                    {{ form.email }}
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <label class="form-label" for="nome">Profissão</label>
                                    {{ form.profissao }}
                                </div>
                            </div>
                        </div>
                    
                    </div>
                    <div class="panel-content d-flex py-2">
                        <div class="ml-auto">
                            <button class="btn btn-primary" type="submit">Enviar</button>
                        </div>
                    </div>
                    </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block javascript %}
<script src="{% static 'js/formplugins/inputmask/inputmask.bundle.js' %}"></script>
<script>
    $(document).ready(function () {
        $(":input").inputmask();
    });

</script>
{% endblock javascript %}

pacientes/templates/pacientes/list.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" media="screen, print" href="{% static 'css/datagrid/datatables/datatables.bundle.css' %}">
{% endblock css %}


{% block nav_inicio %}

    <li>

{% endblock nav_inicio %}


{% block nav_pacientes %}

    <li class="active open">
    
{% endblock nav_pacientes %}


{% block nav_pacientes_listagem %}

<li class="active">

{% endblock nav_pacientes_listagem %}


{% block breadcrumb-item %}

<li class="breadcrumb-item activate">Pacientes</li>
<li class="breadcrumb-item activate">Listagem</li>

{% endblock breadcrumb-item %}
    

{% block subheader_title %}

    <i class='subheader-icon fal fa-address-card'></i> Pacientes

{% endblock subheader_title %}

{% block subheader_subtitle %}

    Listagem dos Pacientes

{% endblock subheader_subtitle %}


{% block subheader_block %}
    

{% endblock subheader_block %}
    
    
{% block content %}
<div class="row">
    <div class="col-xl-12">
        <a href="{% url 'pacientes:paciente_add' %}" class="btn btn-success" id="cadastrar_agendamento">
            <i class="fas fa-plus"></i>
            <span class="hidden-md-down"> Adicionar Paciente</span>
        </a>
    </div>
</div>
<div class="row">&nbsp;</div>
<div class="row">
    <div class="col-xl-12">
        <div id="panel-1" class="panel">
            <div class="panel-hdr">
                <h2>
                    Todos os Pacientes
                </h2>
            </div>
            <div class="panel-container show">
                <div class="panel-content">
                    <table id="dt-basic-example" class="table table-bordered table-hover table-striped w-100">
                        <thead class="text-center">
                            <tr>
                                <th>Nome</th>
                                <th>Telefone</th>
                                <th>Nascimento</th>
                                <th>Cidade</th>
                                <th>UF</th>
                                <th>Profissão</th>
                                <th>Email</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if object_list %}
                                {% for paciente in object_list %}
                                    <tr>
                                        <td>{{ paciente.nome }}</td>
                                        <td>{{ paciente.telefone }}</td>
                                        <td>
                                            <txt alt="{{ paciente.data_nascimento|date:'Y-m-d' }}">
                                                {{ paciente.data_nascimento|default_if_none:"&nbsp;" }}
                                            </txt>
                                        </td>
                                        <td>{{ paciente.cidade|default_if_none:"&nbsp;" }}</td>
                                        <td>{{ paciente.estado|default_if_none:"&nbsp;" }}</td>
                                        <td>{{ paciente.profissao|default_if_none:"&nbsp;" }}</td>
                                        <td>{{ paciente.email|default_if_none:"&nbsp;" }}</td>
                                        <td>
                                            <div class="text-center">
                                                <a href="{% url 'pacientes:paciente_detail' paciente.id %}" class="btn btn-sm btn-outline-success mr-2" title="Detalhes">
                                                    <i class="fal fa-eye "></i> 
                                                </a>
                                                <!--a href="{% url 'pacientes:paciente_edit' paciente.id %}" class="btn btn-sm btn-outline-primary mr-2" title="Editar">
                                                    <i class="fal fa-edit "></i> 
                                                </a-->
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<form id="excluir" method="post">
    {% csrf_token %}
</form>
{% endblock content %}


{% block javascript %}
    <script src="{% static 'js/datagrid/datatables/datatables.bundle.js' %}"></script>
    <script src="{% static 'js/datagrid/datatables/alt-string.js' %}"></script>

    <script>
        $(document).ready(function()
            {
                oTable = $('#dt-basic-example').dataTable(
                {
                    responsive: true,
                    columnDefs: [
                            {
                                type: 'alt-string', targets: 2
                            }
                        ]
                });
            });
    </script>
{% endblock javascript %}
    