procedimentos/urls.py
from django.urls import path

from .views import ProcedimentoListView
from .views import ProcedimentoCreateView
from .views import ProcedimentoUpdateView
from .views import ProcedimentoDeleteView
from .views import ProcedimentoAjaxListView
from .views import ProcedimentoAjaxListView2

from .views import PromocaoListView
from .views import PromocaoDetailView
from .views import PromocaoCreateView
from .views import PromocaoUpdateView
from .views import PromocaoDeleteView

from .views import ProcedimentoPromocaoCreateView
from .views import ProcedimentoPromocaoUpdateView
from .views import ProcedimentoPromocaoDeleteView
from .views import ProcedimentoPromocaoAjaxListView

app_name = 'procedimentos'

urlpatterns = [

    # PROCEDIMENTOS
    path('procedimentos', ProcedimentoListView.as_view(),
         name='procedimento_list'),
    path('procedimentos/adicionar/', ProcedimentoCreateView.as_view(),
         name='procedimento_create'),
    path('procedimentos/<str:id>/editar/', ProcedimentoUpdateView.as_view(),
         name='procedimento_edit'),
    path('procedimentos/<str:id>/excluir/', ProcedimentoDeleteView.as_view(),
         name='procedimento_delete'),

    path('procedimentos/<str:id>/listar/',
         ProcedimentoAjaxListView.as_view(),
         name='procedimento_ajax_list'),
    path('procedimentos/buscar_procedimentos/',
         ProcedimentoAjaxListView2.as_view(),
         name='procedimento_ajax_list2'),

    # PROMOÇÕES
    path('promocoes', PromocaoListView.as_view(),
         name='promocao_list'),
    path('promocoes/<str:pk>/detalhes/', PromocaoDetailView.as_view(),
         name='promocao_detail'),
    path('promocoes/adicionar/', PromocaoCreateView.as_view(),
         name='promocao_create'),
    path('promocoes/<str:id>/editar/', PromocaoUpdateView.as_view(),
         name='promocao_edit'),
    path('promocoes/<str:id>/excluir/', PromocaoDeleteView.as_view(),
         name='promocao_delete'),

    # PROCEDIMENTOS EM PROMOÇÃO
    path('procedimentos_promocoes/adicionar/',
         ProcedimentoPromocaoCreateView.as_view(),
         name='procedimento_promocao_create'),

    path('procedimentos_promocoes/<str:id>/editar/',
         ProcedimentoPromocaoUpdateView.as_view(),
         name='procedimento_promocao_edit'),

    path('procedimentos_promocoes/<str:id>/excluir/',
         ProcedimentoPromocaoDeleteView.as_view(),
         name='procedimento_promocao_delete'),

    path('procedimentos_promocoes/buscar_procedimentos/',
         ProcedimentoPromocaoAjaxListView.as_view(),
         name='procedimento_ajax_list2'),
]

siga/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from siga.views import Index


urlpatterns = [
    path('pacientes/', include('pacientes.urls')),
    path('estetica/', include('procedimentos.urls')),
    path('financeiro/', include('movimentacoes.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('', Index.as_view(), name='home')
]

procedimentos/models.py
""" MODELS DO APP PROCEDIMENTOS """
from django.db import models


# Create your models here.

class Procedimento(models.Model):
    """ MODEL PROCEDIMENTOS """
    class TipoAtendimentoChoices(models.IntegerChoices):
        ESTETICA = 0, 'ESTÉTICA'
        FISIOTERAPIA = 1, 'FISIOTERAPIA'

    nome = models.CharField(max_length=200)
    descricao = models.TextField("Descrição", null=True, blank=True)
    duracao = models.TimeField("Duração", null=True, blank=True)
    valor = models.DecimalField(
        "Valor", max_digits=5, decimal_places=2, default=0.0)
    tipo_atendimento = models.SmallIntegerField(
        "Tipo de Atendimento", choices=TipoAtendimentoChoices.choices,
        default=TipoAtendimentoChoices.ESTETICA)

    class Meta:
        ordering = ['nome']

    def __str__(self):
        return self.nome


class Promocao(models.Model):
    """ MODEL PROMOCAO """
    descricao = models.CharField(max_length=200)
    inicio = models.DateField("Início", null=True, blank=True)
    termino = models.DateField("Término", null=True, blank=True)
    procedimentos = models.ManyToManyField(
        Procedimento, through="ProcedimentoPromocao", blank=True)

    class Meta:
        verbose_name = "Promoção"
        verbose_name_plural = "Promoções"
        ordering = ['descricao']

    def __str__(self):
        return self.descricao


class ProcedimentoPromocao(models.Model):
    """
        MODEL INTERMEDIÁRIO ENTRE PROMOÇÃO E PROCEDIMENTO
    """
    promocao = models.ForeignKey(Promocao, on_delete=models.CASCADE)
    procedimento = models.ForeignKey(Procedimento, on_delete=models.CASCADE)
    valor_promocional = models.DecimalField("Valor Promocional",
                                            max_digits=5,
                                            decimal_places=2,
                                            default=0.0)

    class Meta:
        verbose_name = "Procedimento em Promoção"
        verbose_name_plural = "Procedimentos em Promoções"
        unique_together = ['promocao', 'procedimento']
        order_with_respect_to = 'procedimento'

    def __str__(self):
        return self.promocao.descricao + " - " + self.procedimento.nome

procedimentos/forms.py
""" Formulários """

from django import forms

from .models import Procedimento
from .models import Promocao
from .models import ProcedimentoPromocao


class ProcedimentoForm(forms.ModelForm):
    """Form definition for Procedimento."""

    class Meta:
        """Meta definition for Procedimentoform."""

        model = Procedimento
        fields = ['nome', 'descricao', 'duracao', 'valor']


class PromocaoForm(forms.ModelForm):
    """Form definition for Procedimento."""

    class Meta:
        """Meta definition for Procedimentoform."""

        model = Promocao
        fields = ['descricao', 'inicio', 'termino']


class ProcedimentoPromocaoForm(forms.ModelForm):
    """Form definition for ProcedimentoPromocao."""

    class Meta:
        """Meta definition for Procedimentoform."""

        model = ProcedimentoPromocao
        fields = ['procedimento', 'promocao', 'valor_promocional']

procedimentos/views.py
from django.core import serializers
from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin
from django.db.models import Q, Subquery
from django.forms.models import model_to_dict
from django.http import JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.utils import formats
from django.utils import timezone
from django.urls import reverse_lazy
from django.views.generic import ListView, View, DetailView

from .models import Procedimento
from .models import Promocao
from .models import ProcedimentoPromocao

from .forms import ProcedimentoForm
from .forms import PromocaoForm

# PROCEDIMENTOS #


class ProcedimentoListView(\
    LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Procedimento
    template_name = "procedimento/list.html"
    permission_required = "procedimentos.view_procedimento"
    login_url = reverse_lazy('admin:login')


class ProcedimentoAjaxListView(\
    LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = "procedimentos.view_procedimento"
    login_url = reverse_lazy('admin:login')

    def post(self, request, id):
        pd = Procedimento.objects.all().exclude(
            procedimentopromocao__promocao__id=id)
        return render(request, "procedimento/list_ajax.html",
                      context={'context': pd})


class ProcedimentoCreateView(\
    LoginRequiredMixin, PermissionRequiredMixin, View):
    """ Lista de Formas de Pagamento """

    permission_required = "procedimentos.add_procedimento"
    login_url = reverse_lazy('admin:login')

    def post(self, request):
        form = ProcedimentoForm(request.POST)
        if form.is_valid and request.is_ajax():
            form.save()
            procedimento = form.instance
            return JsonResponse(model_to_dict(procedimento), status=200)
        else:
            return JsonResponse(
                {'result': 'formulario invalido'},
                status=200)


class ProcedimentoUpdateView(\
    LoginRequiredMixin, PermissionRequiredMixin, View):
    """ Lista de Formas de Pagamento """

    permission_required = "procedimentos.change_procedimento"
    login_url = reverse_lazy('admin:login')

    def post(self, request, id):
        procedimento = get_object_or_404(Procedimento, pk=id)
        form = ProcedimentoForm(request.POST, instance=procedimento)
        if form.is_valid and request.is_ajax():
            form.save()
            procedimento = get_object_or_404(Procedimento, pk=id)
            return JsonResponse(model_to_dict(procedimento), status=200)
        else:
            return JsonResponse(
                {'result': 'formulario invalido'},
                status=200)


class ProcedimentoDeleteView(\
    LoginRequiredMixin, PermissionRequiredMixin, View):
    """ Lista de Formas de Pagamento """

    permission_required = "procedimentos.delete_procedimento"
    login_url = reverse_lazy('admin:login')

    def post(self, request, id):
        procedimento = get_object_or_404(Procedimento, pk=id)
        procedimento.delete()
        return JsonResponse({'result': 'ok'}, status=200)


# PROMOÇÕES #


class PromocaoListView(\
    LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Promocao
    template_name = "promocao/list.html"
    permission_required = "procedimentos.view_promocao"
    login_url = reverse_lazy('admin:login')


class PromocaoDetailView(\
    LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Promocao
    template_name = "promocao/detail.html"
    permission_required = "procedimentos.view_promocao"
    login_url = reverse_lazy('admin:login')


class PromocaoCreateView(\
    LoginRequiredMixin, PermissionRequiredMixin, View):
    """ Lista de Formas de Pagamento """
    permission_required = "procedimentos.add_promocao"
    login_url = reverse_lazy('admin:login')

    def post(self, request):
        form = PromocaoForm(request.POST)
        if form.is_valid and request.is_ajax():
            form.save()
            promocao = form.instance
            promocao.inicio = formats.date_format(
                promocao.inicio, r'j \d\e F \d\e Y')
            promocao.termino = formats.date_format(
                promocao.termino, r'j \d\e F \d\e Y')
            return JsonResponse(model_to_dict(promocao), status=200)
        else:
            return JsonResponse(
                {'result': 'formulario invalido'},
                status=200)


class PromocaoUpdateView(\
    LoginRequiredMixin, PermissionRequiredMixin, View):
    """ Lista de Formas de Pagamento """

    permission_required = "procedimentos.change_promocao"
    login_url = reverse_lazy('admin:login')

    def post(self, request, id):
        promocao = get_object_or_404(Promocao, pk=id)
        form = PromocaoForm(request.POST, instance=promocao)
        if form.is_valid and request.is_ajax():
            form.save()
            promocao = get_object_or_404(Promocao, pk=id)
            promocao.inicio = formats.date_format(
                promocao.inicio, r'j \d\e F \d\e Y')
            promocao.termino = formats.date_format(
                promocao.termino, r'j \d\e F \d\e Y')
            return JsonResponse(
                model_to_dict(
                    promocao, fields=[
                        field.name for field in promocao._meta.fields
                    ]), status=200)
        else:
            return JsonResponse(
                {'result': 'formulario invalido'},
                status=200)


class PromocaoDeleteView(\
    LoginRequiredMixin, PermissionRequiredMixin, View):
    """ Lista de Formas de Pagamento """

    permission_required = "procedimentos.delete_promocao"
    login_url = reverse_lazy('admin:login')

    def get(self, request, id):
        return JsonResponse({'mensagem': 'veio pelo get'}, status=200)

    def post(self, request, id):
        promocao = get_object_or_404(Promocao, pk=id)
        promocao.delete()
        return JsonResponse({'result': 'ok'}, status=200)


# PROCEDIMENTOS EM PROMOÇÃO #


class ProcedimentoPromocaoCreateView(\
    LoginRequiredMixin, PermissionRequiredMixin, View):
    """ Lista de Formas de Pagamento """

    permission_required = "procedimentos.add_procedimentopromocao"
    login_url = reverse_lazy('admin:login')

    def post(self, request):
        promocao = request.POST.get('promocao', '')
        procedimento = request.POST.get('procedimento', '')
        valor_promocional = request.POST.get('valor_promocional', '')
        procedimento_promocao = ProcedimentoPromocao(
            None,
            promocao,
            procedimento,
            valor_promocional)
        procedimento_promocao.save()

        procedimento = Procedimento.objects.get(
            id=procedimento_promocao.procedimento.id)

        context = {}
        context['procedimento'] = model_to_dict(procedimento)
        context['procedimento_promocao'] = model_to_dict(procedimento_promocao)

        return JsonResponse(context, status=200)


class ProcedimentoAjaxListView2(\
    LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = "procedimentos.view_procedimentopromocao"
    login_url = reverse_lazy('admin:login')
    
    def get(self, request):
        procedimentos = serializers.serialize('json',
                                              Procedimento.objects.all(),
                                              fields=('id', 'nome', 'valor',))
        return HttpResponse(procedimentos, content_type="application/json")


class ProcedimentoPromocaoUpdateView(\
    LoginRequiredMixin, PermissionRequiredMixin, View):
    """ Lista de Formas de Pagamento """
    permission_required = "procedimentos.change_procedimentopromocao"
    login_url = reverse_lazy('admin:login')

    def post(self, request, id):
        procedimento_promocao = get_object_or_404(ProcedimentoPromocao, pk=id)
        procedimento_promocao.valor_promocional = request.POST.get(
            'valor_promocional', '')
        procedimento_promocao.save()
        return JsonResponse(
            {'valor_promocional': procedimento_promocao.valor_promocional},
            status=200)


class ProcedimentoPromocaoDeleteView(\
    LoginRequiredMixin, PermissionRequiredMixin, View):
    """ Lista de Formas de Pagamento """
    permission_required = "procedimentos.delete_procedimentopromocao"
    login_url = reverse_lazy('admin:login')

    def post(self, request, id):
        procedimento_promocao = get_object_or_404(ProcedimentoPromocao, pk=id)
        procedimento_promocao.delete()
        return JsonResponse({'result': 'ok'}, status=200)


class ProcedimentoPromocaoAjaxListView(\
    LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = "procedimentos.view_procedimentopromocao"
    login_url = reverse_lazy('admin:login')

    def get(self, request):
        pp = ProcedimentoPromocao.objects.filter(
            Q(promocao__termino__gte=timezone.now()),
            Q(promocao__inicio__lte=timezone.now())
        ).order_by('promocao__inicio', 'procedimento__nome')

        promocoes = Promocao.objects.filter(
            id__in=Subquery(pp.values('promocao'))
        ).values('id', 'descricao')

        # p = Procedimento.objects.filter(
        #     id__in=Subquery(pp.values('procedimento')))
        # all = [*pp, *p]
        # data = serializers.serialize('json', pp, indent=4)

        return render(request, "procedimentopromocao/list_ajax.html",
                      context={
                          'procedimentos_promocoes': pp,
                          'promocoes': promocoes
                      })

procedimentos/templates/promocao/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load filters %}


{% block css %}

    <link rel="stylesheet" media="screen, print" href="{% static 'css/datagrid/datatables/datatables.bundle.css' %}">
    <link rel="stylesheet" media="screen, print" href="{% static 'css/notifications/toastr/toastr.css' %}">
    <link rel="stylesheet" media="screen, print" href="{% static 'css/formplugins/select2/select2.bundle.css' %}">

{% endblock css %}


{% block nav_inicio %}

<li>

    {% endblock nav_inicio %}


    {% block nav_promocoes %}

<li class="active">

    {% endblock nav_promocoes %}


    {% block breadcrumb-item %}

<li class="breadcrumb-item activate">Estética</li>
<li class="breadcrumb-item activate">Promoções</li>
<li class="breadcrumb-item activate">Informações</li>

{% endblock breadcrumb-item %}


{% block subheader_title %}

<i class='subheader-icon fal fa-badge-percent'></i> {{ object.descricao }}

{% endblock subheader_title %}

{% block subheader_subtitle %}

Promoção entre os dias <strong>{{ object.inicio|naturalday }}</strong> até <strong>{{ object.termino|naturalday }}</strong>

{% endblock subheader_subtitle %}


{% block subheader_block %}


{% endblock subheader_block %}


{% block content %}
<div class="row">
    <div class="col">
        <a href="javascript:void(0)" id="cadastrar_procedimento" data-id="{{ object.id }}" data-url="{% url 'procedimentos:procedimento_ajax_list' object.id %}" class="btn btn-success font-weight-bold fs-xl">
        <i class="fas fa-plus"></i><i class="fas fa-diagnoses"></i>
           <span class="hidden-md-down ml-1"> Adicionar Procedimento</span>
        </a>
    </div>
</div>
<div class="row">&nbsp;</div>
<div class="row">
    <div class="col-xl-12">
        <div id="panel-1" class="panel">
            <div class="panel-hdr">
                <h2>
                    Lista de Procedimentos em Promoção
                </h2>
            </div>
            <div class="panel-container show">
                <div class="panel-content">
                    <table id="dt-basic-example" class="table table-bordered table-hover table-striped w-100">
                        <thead class="text-center">
                            <tr>
                                <th>Nome</th>
                                <th>Descrição</th>
                                <th>Valor Original</th>
                                <th>Valor Promocional</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for pep  in object.procedimentopromocao_set.all %}
                            <tr>
                                <td>{{ pep.procedimento.nome }}</td>
                                <td>{{ pep.procedimento.descricao }}</td>
                                <td class="text-center">
                                    {{ pep.procedimento.valor }}
                                </td>
                                <td class="text-center">
                                    {{ pep.valor_promocional }}
                                </td>
                                <td>
                                    <div class="text-center">
                                        <a href="javascript:void(0);" id="edit_{{ procedimento.id }}"
                                            class="btn btn-sm btn-primary mr-2 edit_procedimento" title="Editar"
                                            data-nome="{{ pep.procedimento.nome }}"
                                            data-id="{{ pep.id }}"
                                            data-url="{% url 'procedimentos:procedimento_promocao_edit' pep.id %}">
                                            <i class="fas fa-edit "></i>
                                        </a>
                                        <a href="javascript:void(0);" class="btn btn-sm btn-danger mr-2" title="Excluir" id="del_procedimento" data-id="{{ pep.id }}" data-nome="{{ pep.procedimento.nome }}" data-url="{% url 'procedimentos:procedimento_promocao_delete' pep.id %}">
                                            <i class="fas fa-times "></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<form id="excluir" action="{% url 'procedimentos:promocao_delete' object.id %}" method="POST">{% csrf_token %}</form>
{% endblock content %}


{% block javascript %}

<script src="{% static 'js/datagrid/datatables/datatables.bundle.js' %}"></script>
<script src="{% static 'js/datagrid/datatables/alt-string.js' %}"></script>
<script src="{% static 'js/notifications/toastr/toastr.js' %}"></script>
<script src="{% static 'js/formplugins/select2/select2.bundle.js' %}"></script>
<script src="{% static 'js/siga/procedimentos/procedimento_em_promocao/procedimento_em_promocao.js' %}"></script>

{% endblock javascript %}

procedimentos/templates/promocao/list.html
{% extends 'base.html' %}
{% load static %}
{% load filters %}


{% block css %}
    <link rel="stylesheet" media="screen, print" href="{% static 'css/datagrid/datatables/datatables.bundle.css' %}">
    <link rel="stylesheet" media="screen, print" href="{% static 'css/notifications/toastr/toastr.css' %}">
{% endblock css %}


{% block nav_inicio %}

    <li>

{% endblock nav_inicio %}


{% block nav_promocoes %}

    <li class="active"> 

{% endblock nav_promocoes %}


{% block breadcrumb-item %}

    <li class="breadcrumb-item activate">Estética</li>
    <li class="breadcrumb-item activate">Promoções</li>

{% endblock breadcrumb-item %}
    

{% block subheader_title %}

    <i class='subheader-icon fal fa-badge-percent'></i> Promoções

{% endblock subheader_title %}

{% block subheader_subtitle %}

    Promoções de estética que a clínica realiza

{% endblock subheader_subtitle %}


{% block subheader_block %}
    

{% endblock subheader_block %}
    
    
{% block content %}

<div class="row">
    <div class="col-xl-12">
        <a href="javascript:void(0)" data-url="{% url 'procedimentos:promocao_create' %}" class="btn btn-success" id="cadastrar_promocao">
            <i class="fas fa-plus"></i>
            <span class="hidden-md-down"> Cadastrar Promoção</span>
        </a>
    </div>
</div>
<div class="row">&nbsp;</div>
<div class="row">
    <div class="col-xl-12">
        <div id="panel-1" class="panel">
            <div class="panel-hdr">
                <h2>
                    Lista de Promoções
                </h2>
            </div>
            <div class="panel-container show">
                <div class="panel-content">
                    <table id="dt-basic-example" class="table table-bordered table-hover table-striped w-100">
                        <thead class="text-center">
                            <tr>
                                <th>Descrição</th>
                                <th>Início</th>
                                <th>Término</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if object_list %}
                                {% for promocao in object_list %}
                                    <tr>
                                        <td>{{ promocao.descricao }}</td>
                                        <td class="text-center" data-padrao="{{ promocao.inicio|date:'SHORT_DATE_FORMAT' }}">
                                            {{ promocao.inicio }}
                                        </td>
                                        <td class="text-center" data-padrao="{{ promocao.termino|date:'SHORT_DATE_FORMAT' }}">
                                            {{ promocao.termino }}
                                        </td>
                                        <td>
                                            <div class="text-center">
                                                <a href="{% url 'procedimentos:promocao_detail' promocao.id %}" class="btn btn-sm btn-success mr-2" title="Detalhes">
                                                    <i class="fas fa-eye "></i>
                                                </a>
                                                <a href="javascript:void(0);" id="edit_{{ promocao.id }}" class="btn btn-sm btn-primary mr-2 edit_promocao" title="Editar" data-nome="{{ promocao.nome }}" data-descricao="{{ promocao.descricao }}" data-id="{{ promocao.id }}" data-termino="{{ promocao.termino }}" data-url="{% url 'procedimentos:promocao_edit' promocao.id %}">
                                                    <i class="fas fa-edit "></i> 
                                                </a>
                                                <a href="javascript:void(0);" class="btn btn-sm btn-danger mr-2" title="Excluir" id="del_promocao" data-id="{{ promocao.id }}" data-delete-url="{% url 'procedimentos:promocao_delete' promocao.id %}" data-nome="{{ promocao.nome }}">
                                                    <i class="fas fa-times "></i> 
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<form id="form_del_promocao" method="post">
    {% csrf_token %}
</form>
{% endblock content %}


{% block javascript %}
    <script src="{% static 'js/datagrid/datatables/datatables.bundle.js' %}"></script>
    <script src="{% static 'js/data0grid/datatables/alt-string.js' %}"></script>
    <script src="{% static 'js/notifications/toastr/toastr.js' %}"></script>
    <script src="{% static 'js/siga/procedimentos/promocao/promocao.js' %}"></script>
{% endblock javascript %}
    