movimentacoes/urls.py
from django.urls import path
from .views import FormaDePagamentoListView
from .views import FormaDePagamentoListAjaxView
from .views import FormaDePagamentoDeleteView
from .views import FormaDePagamentoUpdateView
from .views import FormaDePagamentoCreateView

from .views import CaixaListView
from .views import CaixaDetailView
from .views import CaixaAbrirView
from .views import CaixaFecharView
from .views import CaixaMovimentacaoView
from .views import CaixaUltimoAbertoAjaxView
from .views import CaixaReceberAjaxView

from .views import AgendamentoCreateView
from .views import AgendamentoListView
from .views import AgendamentosAjaxListView
from .views import AgendamentoAjaxDetailView
from .views import AgendamentoAjaxEditView
from .views import AgendamentoAjaxDeleteView

from .views import MovimentacaoCreateView
from .views import MovimentacaoUpdateView
from .views import MovimentacaoDeleteView

from .views import UsuarioAjaxListView

app_name = 'movimentacoes'

urlpatterns = [
    # FORMAS DE PAGAMENTO
    path('formas_de_pagamento/',
         FormaDePagamentoListView.as_view(),
         name="forma_de_pagamento_list"),

    path('formas_de_pagamento_ajax/',
         FormaDePagamentoListAjaxView.as_view(),
         name="forma_de_pagamento_list_ajax"),

    path('forma_pgto/<str:id>/excluir/',
         FormaDePagamentoDeleteView.as_view(),
         name="forma_de_pagamento_delete"),

    path('forma_pgto/<str:id>/editar/',
         FormaDePagamentoUpdateView.as_view(),
         name="forma_de_pagamento_edit"),

    path('forma_pgto/adicionar/',
         FormaDePagamentoCreateView.as_view(),
         name="forma_de_pagamento_create"),

    # CAIXA
    path('caixas/',
         CaixaListView.as_view(),
         name="caixa_list"),

    path('caixa/movimentacao/',
         CaixaMovimentacaoView.as_view(),
         name="caixa_movimentacao"),

    path('caixa/<str:pk>/detalhes/',
         CaixaDetailView.as_view(),
         name="caixa_detail"),

    path('caixa/<str:id>/fechar/',
         CaixaFecharView.as_view(),
         name="caixa_fechar"),

    path('caixa/receber/<str:id>/',
         CaixaReceberAjaxView.as_view(),
         name="caixa_receber"),

    path('caixa/adicionar/',
         CaixaAbrirView.as_view(),
         name="caixa_abrir"),

    path('caixa/aberto_ajax/',
         CaixaUltimoAbertoAjaxView.as_view(),
         name="caixa_aberto"),

    # AGENDAMENTOS

    path('agendamentos/',
         AgendamentoListView.as_view(),
         name="agendamento_list"),

    path('agendamentos/adicionar/',
         AgendamentoCreateView.as_view(),
         name="agendamento_create"),

    path('agendamentos/lista_ajax/',
         AgendamentosAjaxListView.as_view(),
         name="agendamento_list_ajax"),

    path('agendamentos/detalhe_ajax/<str:id>/',
         AgendamentoAjaxDetailView.as_view(),
         name="agendamento_detail_ajax"),

    path('agendamentos/editar_ajax/<str:id>/',
         AgendamentoAjaxEditView.as_view(),
         name="agendamento_edit_ajax"),

    path('agendamentos/excluir_ajax/<str:id>/',
         AgendamentoAjaxDeleteView.as_view(),
         name="agendamento_delete_ajax"),

    # PROFISSIONAIS

    path('usuarios/buscar_profissionais/',
         UsuarioAjaxListView.as_view(),
         name="agendamento_lista_ajax"),

    # MOVIMENTAÇÕES
    path('movimentacao/<str:id>/excluir/',
         MovimentacaoDeleteView.as_view(),
         name="movimentacao_delete"),

    path('movimentacao/adicionar/',
         MovimentacaoCreateView.as_view(),
         name="movimentacao_create"),

    path('movimentacao/<str:id>/editar/',
         MovimentacaoUpdateView.as_view(),
         name="movimentacao_edit"),
]

pacientes/urls.py
from django.urls import path

from .views import PacienteListView
from .views import PacienteCreateView
from .views import PacienteUpdateView
from .views import PacienteDeleteView
from .views import PacienteDetailView
from .views import PacienteListAjaxView
from .views import PacienteCreateAjaxView

app_name = 'pacientes'

urlpatterns = [
    path('', PacienteListView.as_view(), name="paciente_list"),
    path('adicionar/', PacienteCreateView.as_view(), name="paciente_add"),
    path('adicionar/ajax/', PacienteCreateAjaxView.as_view(),
         name="paciente_add_ajax"),
    path('buscar_pacientes/', PacienteListAjaxView.as_view(),
         name="paciente_buscar"),
    path('<int:pk>/editar/', PacienteUpdateView.as_view(),
         name="paciente_edit"),
    path('<int:pk>/excluir/', PacienteDeleteView.as_view(),
         name="paciente_delete"),
    path('<int:pk>/detalhes/', PacienteDetailView.as_view(),
         name="paciente_detail"),
]

siga/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from siga.views import Index


urlpatterns = [
    path('pacientes/', include('pacientes.urls')),
    path('estetica/', include('procedimentos.urls')),
    path('financeiro/', include('movimentacoes.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('', Index.as_view(), name='home')
]

movimentacoes/models.py
from django.db import models
from django.contrib.auth.models import User

from pacientes.models import Paciente
from procedimentos.models import Procedimento, ProcedimentoPromocao


class Usuario(models.Model):
    class FuncaoDoUsuario(models.IntegerChoices):
        ADMINISTRADOR = 1, 'ADMINISTRADOR'
        ESTETICISTA = 2, 'ESTETICISTA'

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    funcao = models.SmallIntegerField("Função",
                                      choices=FuncaoDoUsuario.choices,
                                      default=FuncaoDoUsuario.ESTETICISTA
                                      )

    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Usuários"

    def __str__(self):
        return self.user.first_name


class Caixa(models.Model):
    operador = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    data = models.DateField()
    abertura = models.TimeField()
    fechamento = models.TimeField(null=True, blank=True)
    saldo_inicial = models.DecimalField(
        "Saldo Inicial", max_digits=7, decimal_places=2, null=True, blank=True)
    saldo = models.DecimalField(
        "Saldo", max_digits=7, decimal_places=2, null=True, blank=True)
    status = models.BooleanField("Aberto", default=1)

    class Meta:
        verbose_name = "Caixa"
        verbose_name_plural = "Caixas"

    def __str__(self):
        return str(self.data)


class Agendamento(models.Model):
    class SituacaoDoAgendamento(models.IntegerChoices):
        ACONFIRMAR = 0, 'A CONFIRMAR'
        CONFIRMADO = 1, 'CONFIRMADO'
        EMESPERA = 2, 'EM ESPERA'
        EMATENDIMENTO = 3, 'EM ATENDIMENTO'
        ENCERRADO = 4, 'ENCERRADO'

    paciente = models.ForeignKey(Paciente,
                                 on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario,
                                on_delete=models.CASCADE)
    profissional = models.ForeignKey(Usuario, related_name="profissional",
                                     on_delete=models.CASCADE)
    data = models.DateField()
    horario = models.TimeField("Horário")
    observacoes = models.TextField("Observações",
                                   null=True,
                                   blank=True)
    status = models.SmallIntegerField(
        "Situação",
        choices=SituacaoDoAgendamento.choices,
        default=SituacaoDoAgendamento.ACONFIRMAR
    )
    procedimentos = models.ManyToManyField(Procedimento,
                                           blank=True)
    procedimentos_promo = models.ManyToManyField(
        ProcedimentoPromocao,
        verbose_name="Procedimentos em Promoção",
        blank=True
    )
    valor = models.DecimalField(
        "Valor", max_digits=7, decimal_places=2, default=0)

    valor_diferenciado = models.BooleanField(
        "Valor Diferenciado", default=False)

    desconto = models.DecimalField(
        "Desconto", max_digits=7, decimal_places=2, default=0,
        null=True, blank=True)

    class Meta:
        verbose_name = "Agendamento"
        verbose_name_plural = "Agendamentos"
        unique_together = ['profissional', 'horario', 'data']

    def __str__(self):
        return self.paciente.nome + " - " + \
            self.usuario.user.first_name + " - " + \
            str(self.data) + " " + str(self.horario)


class FormaDePagamento(models.Model):
    nome = models.CharField("Descrição", max_length=50)
    acrescimo = models.DecimalField("Acréscimo",
                                    max_digits=6,
                                    decimal_places=4,
                                    default=0,
                                    null=True,
                                    blank=True)
    desconto = models.DecimalField("Desconto",
                                   max_digits=6,
                                   decimal_places=4,
                                   default=0,
                                   null=True,
                                   blank=True)

    class Meta:
        verbose_name = "Forma de Pagamento"
        verbose_name_plural = "Formas de Pagamentos"

    def __str__(self):
        return self.nome


class AgendamentoPagamento(models.Model):
    agendamento = models.ForeignKey(
        Agendamento, on_delete=models.CASCADE)
    caixa = models.ForeignKey(
        Caixa, on_delete=models.CASCADE)
    forma_pagamento = models.ForeignKey(
        FormaDePagamento, on_delete=models.CASCADE)
    valor_pago = models.DecimalField(
        "Valor Pago", max_digits=5, decimal_places=2)
    horario = models.DateTimeField("Horário", null=True, blank=True)

    class Meta:
        verbose_name = "Registro de Pagamento do Agendamento"
        verbose_name_plural = "Registros de Pagamentos dos Agendamentos"


class Movimentacao(models.Model):
    class TipoMovimentacao(models.IntegerChoices):
        ENTRADA = 0, 'ENTRADA'
        SAIDA = 1, 'SAÍDA'

    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    caixa = models.ForeignKey(Caixa, on_delete=models.CASCADE)
    forma_pagamento = models.ForeignKey(
        FormaDePagamento, on_delete=models.CASCADE)
    descricao = models.TextField("Descrição")
    natureza = models.CharField(max_length=200)
    tipo = models.SmallIntegerField(
        choices=TipoMovimentacao.choices,
        default=TipoMovimentacao.ENTRADA)
    horario = models.DateTimeField("Horário")
    valor = models.DecimalField(max_digits=7, decimal_places=2)

    class Meta:
        verbose_name = "Registro de Movimentação"
        verbose_name_plural = "Registros de Movimentações"

movimentacoes/forms.py
""" Formulários """

from django import forms

from .models import FormaDePagamento


class FormaDePagamentoForm(forms.ModelForm):
    """Form definition for FormaDePagamento."""

    class Meta:
        """Meta definition for FormaDePagamentoform."""

        model = FormaDePagamento
        fields = ('nome', 'acrescimo', 'desconto')

movimentacoes/templates/movimentacoes/agendamentos/edit.html
`<form id="id_form_editar" class="need-validation" novalidate>
    <h3>Selecionar Paciente</h3>
    <hr>
    <div class="row">
        <div class="col">
            <a href="javascript:void(0);" class="btn btn-success" id="id_novo_paciente"
                data-url="{% url 'pacientes:paciente_add_ajax' %}"><i class="fas fa-plus"></i> Novo Paciente</a>
        </div>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label class="form-label" for="id_buscar_paciente">Buscar Paciente</label>
                <select id="id_buscar_paciente" class="form-control input-md border border-info" required>
                    <option value=""></option>
                </select>
                <div class="invalid-feedback">Selecione um Paciente</div>
            </div>
        </div>
    </div>
    <h3>Agendamento</h3>
    <hr>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label class="form-label" for="id_buscar_profissionais">
                    Profissional
                </label>
                <select name="profissional" id="id_buscar_profissionais" class="form-control" required>
                    <option value=""></option>
                </select>
                <div class="invalid-feedback">Selecione um Profissional</div>
            </div>
        </div>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label class="form-label">Data</label>
                <input type="text" class="form-control input" id="id_data" required>
                <div class="invalid-feedback">Selecione uma data</div>
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label class="form-label">Horário</label>
                <input type="time" class="form-control input" id="id_horario" required>
                <div class="invalid-feedback">Digite o Horário de Atendimento</div>
            </div>
        </div>
    </div>
    <h3>Selcionar Procedimento(s)</h3>
    <hr>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label class="form-label" for="id_buscar_promocionais">Promocionais</label>
                <select name="promocionais" id="id_buscar_promocionais" class="form-control input-md border border-info"
                    multiple="multiple" required>
                    <option value=""></option>
                </select>
                <div class="invalid-feedback">Selecione um procedimento</div>
            </div>
        </div>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label class="form-label" for="id_buscar_procedimentos">Procedimento</label>
                <select name="procedimentos[]" id="id_buscar_procedimentos" class="form-control" multiple="multiple"
                    required>
                    <option value=""></option>
                </select>
                <div class="invalid-feedback">Selecione um procedimento</div>
            </div>
        </div>
    </div>
    <label class="form-label">Observações</label>
    <textarea id="id_observacoes" cols="30" rows="10" class="form-control"></textarea>
</form>`

movimentacoes/templates/movimentacoes/agendamentos/form.html
{% extends 'base.html' %}
{% load static %}


{% block css %}

<link rel="stylesheet" media="screen, print" href="{% static 'css/formplugins/smartwizard/smartwizard.css' %}">
<link rel="stylesheet" media="screen, print" href="{% static 'css/formplugins/select2/select2.bundle.css' %}">
<link rel="stylesheet" media="screen, print" href="{% static 'css/miscellaneous/fullcalendar/fullcalendar.bundle.css' %}">
<link rel="stylesheet" media="screen, print" href="{% static 'css/formplugins/bootstrap-datepicker/bootstrap-datepicker.css' %}">
<link rel="stylesheet" media="screen, print" href="{% static 'css/notifications/toastr/toastr.css' %}">

{% endblock css %}


{% block nav_inicio %}

<li>

{% endblock nav_inicio %}


{% block nav_agendamentos %}

<li class="active open">

{% endblock nav_agendamentos %}

{% block nav_agendamentos_cadastrar %}

<li class="active">

{% endblock nav_agendamentos_cadastrar %}


{% block breadcrumb-item %}

<li class="breadcrumb-item activate"><a href="{% url 'movimentacoes:agendamento_list' %}">Agendamentos</a></li>

<li class="breadcrumb-item activate">Adicionar</li>

{% endblock breadcrumb-item %}


{% block subheader_title %}

<i class='subheader-icon fal fa-address-book'></i> Agendamentos: <span class="fw-300">Adicionar</span>

{% endblock subheader_title %}

{% block subheader_subtitle %}

Agendar Paciente

{% endblock subheader_subtitle %}


{% block subheader_block %}

{% endblock subheader_block %}


{% block content %}

<div class="row">
    <div class="col-xl-12">
        <div id="panel-1" class="panel">
            <div class="panel-hdr">
                <h2>
                    Agendar Paciente
                </h2>
            </div>
            <div class="panel-container show">
                <div id="smartwizard">
                    <ul>
                        <li><a href="#step-1">Agendamento</a></li>
                        <li><a href="#step-2">Procedimento</a></li>
                        <li><a href="#step-3">Observações</a></li>
                        <li><a href="#step-4">Conclusão</a></li>
                    </ul>
                    <div class="p-3">
                        <div id="step-1" class="">
                            <form id="form-step-0" class="need-validation" novalidate>
                                <h3>Agendamento</h3>
                                <hr>
                                <div class="row">
                                    <div class="col">
                                        <a href="javascript:void(0);" class="btn btn-success" id="id_novo_paciente" data-url="{% url 'pacientes:paciente_add_ajax' %}"><i class="fas fa-plus"></i> Novo Paciente</a>
                                    </div>
                                </div>
                                <div class="row">&nbsp;</div>
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label class="form-label" for="id_buscar_paciente">Buscar Paciente</label>
                                            <select id="id_buscar_paciente" class="form-control input-md border border-info" required>
                                                <option value=""></option>
                                            </select>
                                            <div class="invalid-feedback">Selecione um Paciente</div>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label class="form-label" for="id_buscar_profissionais">
                                                Profissional
                                            </label>
                                            <select name="profissional" id="id_buscar_profissionais" class="form-control" required>
                                                <option value=""></option>
                                            </select>
                                            <div class="invalid-feedback">Selecione um Profissional</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">&nbsp;</div>
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label class="form-label">Data</label>
                                            <input type="text" class="form-control input" id="id_data" required>
                                            <div class="invalid-feedback">Selecione uma data</div>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label class="form-label">Horário</label>
                                            <input type="time" class="form-control input" id="id_horario" required>
                                            <div class="invalid-feedback">Digite o Horário de Atendimento</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">&nbsp;</div>
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label class="form-label" id="id_agendamentos_profissional">Agendamentos</label>
                                            <hr>
                                            <!-- Carregar os dados ao selecionar o dia -->
                                            <div id="id_carrega_agendamentos">Selecione um dia para exibir os agendamentos aqui!</div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div id="step-2" class="">
                            <form id="form-step-1" class="need-validation" novalidate>
                                <h3>Selcionar Procedimento(s)</h3>
                                <hr>
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label class="form-label" for="id_buscar_promocionais">Promocionais</label>
                                            <select name="promocionais" id="id_buscar_promocionais" class="form-control input-md border border-info" multiple="multiple" required>
                                                <option value=""></option>
                                            </select>
                                            <div class="invalid-feedback">Selecione um procedimento</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">&nbsp;</div>
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label class="form-label" for="id_buscar_procedimentos">Procedimento</label>
                                            <select name="procedimentos" id="id_buscar_procedimentos" class="form-control " multiple="multiple"
                                                required>
                                            </select>
                                            <div class="invalid-feedback">Selecione um procedimento</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">&nbsp;</div>
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            <div class="custom-control custom-switch">
                                                <input type="checkbox" class="custom-control-input" id="id_valor_diferenciado">
                                                <label class="custom-control-label" for="id_valor_diferenciado">Valor Diferenciado</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">&nbsp;</div>
                                <div class="row" id="id_linha_valor" style="display: none">
                                    <div class="col">
                                        <div class="form-group">
                                            <label class="form-label">Valor</label>
                                            <input type="number" class="form-control input none" min="0.00" step="0.01" value="0.00" id="id_input_valor_diferenciado" required>
                                            <div class="invalid-feedback">Digite um valor válido</div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div id="step-3" class="">
                            <label class="form-label">Observações</label>
                            <textarea id="id_observacoes" cols="30" rows="10" class="form-control"></textarea>
                        </div>
                        <div id="step-4" class="">
                            <div id="resumo">
                                <dl class="row fs-xl">
                                    <dt class="col-sm-2">Paciente</dt>
                                    <dl class="col-sm-10" id="id_conclusao_paciente"></dl>
                                    <dt class="col-sm-2">Telefone</dt>
                                    <dl class="col-sm-10" id="id_conclusao_telefone"></dl>
                                    <dt class="col-sm-2">Profissional</dt>
                                    <dl class="col-sm-10" id="id_conclusao_profissional"></dl>
                                    <dt class="col-sm-2">Dia/Horário</dt>
                                    <dl class="col-sm-10" id="id_conclusao_dia_horario"></dl>
                                    <dt class="col-sm-2">Procedimentos</dt>
                                    <dl class="col-sm-10" id="id_conclusao_procedimentos"></dl>
                                    <dt class="col-sm-2 valor-diferenciado">Valor Diferenciado</dt>
                                    <dl class="col-sm-10 valor-diferenciado" id="id_conclusao_valor"></dl>
                                    <dt class="col-sm-2">Observações</dt>
                                    <dl class="col-sm-10" id="id_conclusao_observacoes"></dl>
                                </dl>
                                <div class="row">
                                    <div class="col-md-4">
                                        <a href="javascript:void(0);" class="btn btn-primary btn-block" id="id_salvar"><i class="fas fa-check"></i> Salvar</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<form>{% csrf_token %}</form>

{% endblock content %}


{% block javascript %}
<script src="{% static 'js/formplugins/inputmask/inputmask.bundle.js' %}"></script>
<script src="{% static 'js/formplugins/smartwizard/smartwizard.js' %}"></script>
<script src="{% static 'js/formplugins/select2/select2.bundle.js' %}"></script>
<script src="{% static 'js/notifications/toastr/toastr.js' %}"></script>
<script src="{% static 'js/dependency/moment/moment.js' %}"></script>
<script src="{% static 'js/dependency/locale/pt-br.js' %}"></script>
<script src="{% static 'js/formplugins/bootstrap-datepicker/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/siga/movimentacoes/agendamentos/agendamento.js' %}"></script>
{% endblock javascript %}

movimentacoes/templates/movimentacoes/agendamentos/list_ajax.html
{% if object_list %}
    <dl class="row">
        {% for agendamento in object_list %}
            <dt class="col-sm-2">{{ agendamento.horario }} ({{ agendamento.profissional.user.first_name  }})</dt>
            <dd class="col-sm-10"> {{ agendamento.paciente.nome }}</dd>
            <dt class="col-sm-2">
                <span class="text-primary">Procedimentos</span>
            </dt>
            <dd class="col-sm-10">
                <span class="text-primary procedimentos_agendados">{% for procedimento in agendamento.procedimentos.all %}{{ procedimento.nome }}, {% endfor %}{% for procedimento in agendamento.procedimentos_promo.all %}{{ procedimento.procedimento.nome }}, {% endfor %}</span>
            </dd>
        {% endfor %}
    </dl>
{% else %} 
<span class="procedimentos_agendados">Não há agendamentos marcados para esse dia</span>
{% endif %}