movimentacoes/urls.py
from django.urls import path
from .views import FormaDePagamentoListView
from .views import FormaDePagamentoListAjaxView
from .views import FormaDePagamentoDeleteView
from .views import FormaDePagamentoUpdateView
from .views import FormaDePagamentoCreateView

from .views import CaixaListView
from .views import CaixaDetailView
from .views import CaixaAbrirView
from .views import CaixaFecharView
from .views import CaixaMovimentacaoView
from .views import CaixaUltimoAbertoAjaxView
from .views import CaixaReceberAjaxView

from .views import AgendamentoCreateView
from .views import AgendamentoListView
from .views import AgendamentosAjaxListView
from .views import AgendamentoAjaxDetailView
from .views import AgendamentoAjaxEditView
from .views import AgendamentoAjaxDeleteView

from .views import MovimentacaoCreateView
from .views import MovimentacaoUpdateView
from .views import MovimentacaoDeleteView

from .views import UsuarioAjaxListView

app_name = 'movimentacoes'

urlpatterns = [
    # FORMAS DE PAGAMENTO
    path('formas_de_pagamento/',
         FormaDePagamentoListView.as_view(),
         name="forma_de_pagamento_list"),

    path('formas_de_pagamento_ajax/',
         FormaDePagamentoListAjaxView.as_view(),
         name="forma_de_pagamento_list_ajax"),

    path('forma_pgto/<str:id>/excluir/',
         FormaDePagamentoDeleteView.as_view(),
         name="forma_de_pagamento_delete"),

    path('forma_pgto/<str:id>/editar/',
         FormaDePagamentoUpdateView.as_view(),
         name="forma_de_pagamento_edit"),

    path('forma_pgto/adicionar/',
         FormaDePagamentoCreateView.as_view(),
         name="forma_de_pagamento_create"),

    # CAIXA
    path('caixas/',
         CaixaListView.as_view(),
         name="caixa_list"),

    path('caixa/movimentacao/',
         CaixaMovimentacaoView.as_view(),
         name="caixa_movimentacao"),

    path('caixa/<str:pk>/detalhes/',
         CaixaDetailView.as_view(),
         name="caixa_detail"),

    path('caixa/<str:id>/fechar/',
         CaixaFecharView.as_view(),
         name="caixa_fechar"),

    path('caixa/receber/<str:id>/',
         CaixaReceberAjaxView.as_view(),
         name="caixa_receber"),

    path('caixa/adicionar/',
         CaixaAbrirView.as_view(),
         name="caixa_abrir"),

    path('caixa/aberto_ajax/',
         CaixaUltimoAbertoAjaxView.as_view(),
         name="caixa_aberto"),

    # AGENDAMENTOS

    path('agendamentos/',
         AgendamentoListView.as_view(),
         name="agendamento_list"),

    path('agendamentos/adicionar/',
         AgendamentoCreateView.as_view(),
         name="agendamento_create"),

    path('agendamentos/lista_ajax/',
         AgendamentosAjaxListView.as_view(),
         name="agendamento_list_ajax"),

    path('agendamentos/detalhe_ajax/<str:id>/',
         AgendamentoAjaxDetailView.as_view(),
         name="agendamento_detail_ajax"),

    path('agendamentos/editar_ajax/<str:id>/',
         AgendamentoAjaxEditView.as_view(),
         name="agendamento_edit_ajax"),

    path('agendamentos/excluir_ajax/<str:id>/',
         AgendamentoAjaxDeleteView.as_view(),
         name="agendamento_delete_ajax"),

    # PROFISSIONAIS

    path('usuarios/buscar_profissionais/',
         UsuarioAjaxListView.as_view(),
         name="agendamento_lista_ajax"),

    # MOVIMENTAÇÕES
    path('movimentacao/<str:id>/excluir/',
         MovimentacaoDeleteView.as_view(),
         name="movimentacao_delete"),

    path('movimentacao/adicionar/',
         MovimentacaoCreateView.as_view(),
         name="movimentacao_create"),

    path('movimentacao/<str:id>/editar/',
         MovimentacaoUpdateView.as_view(),
         name="movimentacao_edit"),
]

siga/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from siga.views import Index


urlpatterns = [
    path('pacientes/', include('pacientes.urls')),
    path('estetica/', include('procedimentos.urls')),
    path('financeiro/', include('movimentacoes.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('', Index.as_view(), name='home')
]

movimentacoes/models.py
from django.db import models
from django.contrib.auth.models import User

from pacientes.models import Paciente
from procedimentos.models import Procedimento, ProcedimentoPromocao


class Usuario(models.Model):
    class FuncaoDoUsuario(models.IntegerChoices):
        ADMINISTRADOR = 1, 'ADMINISTRADOR'
        ESTETICISTA = 2, 'ESTETICISTA'

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    funcao = models.SmallIntegerField("Função",
                                      choices=FuncaoDoUsuario.choices,
                                      default=FuncaoDoUsuario.ESTETICISTA
                                      )

    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Usuários"

    def __str__(self):
        return self.user.first_name


class Caixa(models.Model):
    operador = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    data = models.DateField()
    abertura = models.TimeField()
    fechamento = models.TimeField(null=True, blank=True)
    saldo_inicial = models.DecimalField(
        "Saldo Inicial", max_digits=7, decimal_places=2, null=True, blank=True)
    saldo = models.DecimalField(
        "Saldo", max_digits=7, decimal_places=2, null=True, blank=True)
    status = models.BooleanField("Aberto", default=1)

    class Meta:
        verbose_name = "Caixa"
        verbose_name_plural = "Caixas"

    def __str__(self):
        return str(self.data)


class Agendamento(models.Model):
    class SituacaoDoAgendamento(models.IntegerChoices):
        ACONFIRMAR = 0, 'A CONFIRMAR'
        CONFIRMADO = 1, 'CONFIRMADO'
        EMESPERA = 2, 'EM ESPERA'
        EMATENDIMENTO = 3, 'EM ATENDIMENTO'
        ENCERRADO = 4, 'ENCERRADO'

    paciente = models.ForeignKey(Paciente,
                                 on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario,
                                on_delete=models.CASCADE)
    profissional = models.ForeignKey(Usuario, related_name="profissional",
                                     on_delete=models.CASCADE)
    data = models.DateField()
    horario = models.TimeField("Horário")
    observacoes = models.TextField("Observações",
                                   null=True,
                                   blank=True)
    status = models.SmallIntegerField(
        "Situação",
        choices=SituacaoDoAgendamento.choices,
        default=SituacaoDoAgendamento.ACONFIRMAR
    )
    procedimentos = models.ManyToManyField(Procedimento,
                                           blank=True)
    procedimentos_promo = models.ManyToManyField(
        ProcedimentoPromocao,
        verbose_name="Procedimentos em Promoção",
        blank=True
    )
    valor = models.DecimalField(
        "Valor", max_digits=7, decimal_places=2, default=0)

    valor_diferenciado = models.BooleanField(
        "Valor Diferenciado", default=False)

    desconto = models.DecimalField(
        "Desconto", max_digits=7, decimal_places=2, default=0,
        null=True, blank=True)

    class Meta:
        verbose_name = "Agendamento"
        verbose_name_plural = "Agendamentos"
        unique_together = ['profissional', 'horario', 'data']

    def __str__(self):
        return self.paciente.nome + " - " + \
            self.usuario.user.first_name + " - " + \
            str(self.data) + " " + str(self.horario)


class FormaDePagamento(models.Model):
    nome = models.CharField("Descrição", max_length=50)
    acrescimo = models.DecimalField("Acréscimo",
                                    max_digits=6,
                                    decimal_places=4,
                                    default=0,
                                    null=True,
                                    blank=True)
    desconto = models.DecimalField("Desconto",
                                   max_digits=6,
                                   decimal_places=4,
                                   default=0,
                                   null=True,
                                   blank=True)

    class Meta:
        verbose_name = "Forma de Pagamento"
        verbose_name_plural = "Formas de Pagamentos"

    def __str__(self):
        return self.nome


class AgendamentoPagamento(models.Model):
    agendamento = models.ForeignKey(
        Agendamento, on_delete=models.CASCADE)
    caixa = models.ForeignKey(
        Caixa, on_delete=models.CASCADE)
    forma_pagamento = models.ForeignKey(
        FormaDePagamento, on_delete=models.CASCADE)
    valor_pago = models.DecimalField(
        "Valor Pago", max_digits=5, decimal_places=2)
    horario = models.DateTimeField("Horário", null=True, blank=True)

    class Meta:
        verbose_name = "Registro de Pagamento do Agendamento"
        verbose_name_plural = "Registros de Pagamentos dos Agendamentos"


class Movimentacao(models.Model):
    class TipoMovimentacao(models.IntegerChoices):
        ENTRADA = 0, 'ENTRADA'
        SAIDA = 1, 'SAÍDA'

    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    caixa = models.ForeignKey(Caixa, on_delete=models.CASCADE)
    forma_pagamento = models.ForeignKey(
        FormaDePagamento, on_delete=models.CASCADE)
    descricao = models.TextField("Descrição")
    natureza = models.CharField(max_length=200)
    tipo = models.SmallIntegerField(
        choices=TipoMovimentacao.choices,
        default=TipoMovimentacao.ENTRADA)
    horario = models.DateTimeField("Horário")
    valor = models.DecimalField(max_digits=7, decimal_places=2)

    class Meta:
        verbose_name = "Registro de Movimentação"
        verbose_name_plural = "Registros de Movimentações"

movimentacoes/forms.py
""" Formulários """

from django import forms

from .models import FormaDePagamento


class FormaDePagamentoForm(forms.ModelForm):
    """Form definition for FormaDePagamento."""

    class Meta:
        """Meta definition for FormaDePagamentoform."""

        model = FormaDePagamento
        fields = ('nome', 'acrescimo', 'desconto')

movimentacoes/templates/movimentacoes/caixas/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load filters %}


{% block css %}

    <link rel="stylesheet" media="screen, print" href="{% static 'css/datagrid/datatables/datatables.bundle.css' %}">
    <link rel="stylesheet" media="screen, print" href="{% static 'css/notifications/toastr/toastr.css' %}">
    <link rel="stylesheet" media="screen, print" href="{% static 'css/formplugins/select2/select2.bundle.css' %}">

{% endblock css %}


{% block nav_inicio %}

<li>

{% endblock nav_inicio %}


{% block nav_financeiro %}

<li class="active open">

{% endblock nav_financeiro %}

{% block nav_financeiro_caixa_movimentacao %}

<li class="active">

{% endblock nav_financeiro_caixa_movimentacao %}


{% block breadcrumb-item %}

<li class="breadcrumb-item activate">Financeiro</li>
<li class="breadcrumb-item activate">Caixas</li>

{% if object.status %}

    <li class="breadcrumb-item activate">Movimentação</li>

{% else %}

<li class="breadcrumb-item activate">Histórico</li>

{% endif %}

{% endblock breadcrumb-item %}


{% block subheader_title %}

<i class='subheader-icon fal fa-cash-register'></i> 

{% if object.status %}
<span class="badge badge-success">Caixa Aberto</span>
{% else %}
<span class="badge badge-warning">Caixa Fechado</span>
{% endif %}
    

{% endblock subheader_title %}

{% block subheader_subtitle %}

Movimentação do Caixa

{% endblock subheader_subtitle %}


{% block subheader_block %}


{% endblock subheader_block %}


{% block content %}
<div class="row">
    <div class="col-sm-6 col-lg-3">
        <div class="p-2 bg-info-300 rounded overflow-hidden position-relative text-white mb-g">
            <div class="">
                <h3 class="display-4 d-block l-h-n m-0 fw-500">
                    R$ <span id="card_saldo">{{ object.saldo }}</span>
                    <small class="m-0 l-h-n"><b>Saldo</b></small>
                </h3>
            </div>
            <i class="fal fa-cash-register position-absolute pos-right pos-bottom opacity-20 mb-n1 mr-n1"
                style="font-size: 5.5rem"></i>
        </div>
    </div>
    {% for dado in dados1 %}
        <!--div class="col-sm-6 col-lg-3">
            <div class="p-2 bg-primary-300 rounded overflow-hidden position-relative text-white mb-g">
                <div class="">
                    <h3 class="display-4 d-block l-h-n m-0 fw-500">R$ {{ dado.soma }}<small class="m-0 l-h-n"><b>{{ dado.forma_pagamento }}</b></small>
                    </h3>
                </div>
                {% if dado.forma_pagamento == 'DÉBITO' or dado.forma_pagamento == 'CRÉDITO À VISTA' or dado.forma_pagamento == 'CRÉDITO 2X' %}
                    <i class="fal fa-credit-card position-absolute pos-right pos-bottom opacity-20 mb-n1 mr-n1"
                    style="font-size: 5.5rem"></i>
                {% elif dado.forma_pagamento == 'TRANSFERÊNCIA' %}
                    <i class="fal fa-mobile-android-alt position-absolute pos-right pos-bottom opacity-20 mb-n1 mr-n1"
                    style="font-size: 5.5rem"></i>
                {% else %}
                    <i class="fal fa-money-bill-wave position-absolute pos-right pos-bottom opacity-20 mb-n1 mr-n1"
                    style="font-size: 5.5rem"></i>
                {% endif %}
            </div>
        </div-->
    {% endfor %}
</div>
{% if object.status %}
<div class="row">
    <div class="col">
        <a href="javascript:void(0)" data-url="{% url 'movimentacoes:movimentacao_create' %}" id="movimentar_caixa" data-id="{{ object.id }}" class="btn btn-success btn-block font-weight-bold fs-lg">
        <i class="fas fa-plus"></i> <i class="fas fa-exchange"></i>
           <span class="hidden-md-down ml-1"> Movimentar Caixa</span>
        </a>
    </div>
    <div class="col">
        <a href="javascript:void(0)" id="fechar_caixa" data-id="{{ object.id }}" data-url="{% url 'movimentacoes:caixa_fechar' object.id %}" class="btn btn-danger btn-block font-weight-bold fs-lg">
        <i class="fas fa-window-close"></i> <i class="fas fa-cash-register"></i>
           <span class="hidden-md-down ml-1"> Fechar Caixa</span>
        </a>
    </div>
    <div class="col">&nbsp;</div>
    <div class="col">&nbsp;</div>
</div>
<div class="row">&nbsp;</div>
{% endif %}
<div class="row">
    <div class="col-xl-12">
        <div id="panel-1" class="panel">
            <div class="panel-hdr">
                <h2>
                    Entradas e Saídas
                </h2>
            </div>
            <div class="panel-container show">
                <div class="panel-content">
                    <table id="dt-basic-example" class="table table-bordered table-hover table-striped w-100">
                        <thead class="text-center">
                            <tr>
                                <th>Horário</th>
                                <th>Descrição</th>
                                <th>Natureza</th>
                                <th>Tipo</th>
                                <th>Meio</th>
                                <th>Valor</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for agp  in object.agendamentopagamento_set.all %}
                                <tr>
                                    <td class="text-center">{{ agp.horario|date:'SHORT_DATETIME_FORMAT' }}</td>
                                    <td>{{ agp.agendamento.paciente.nome|truncatewords:2 }}, {{ agp.agendamento.data|date:'SHORT_DATE_FORMAT' }} às {{ agp.agendamento.horario }} | {{ agp.agendamento.profissional.user.first_name }}</td>
                                    <td>Atendimento</td>
                                    <td class="text-center"><span class="badge border border-success text-success">Entrada</span></td>
                                    <td>{{ agp.forma_pagamento.nome }}</td>
                                    <td>R$ {{ agp.valor_pago }}</td>
                                    <td></td>
                                </tr>
                            {% endfor %}
                            {% for mov in object.movimentacao_set.all  %}
                                <tr>
                                    <td class="text-center">{{ mov.horario|date:'SHORT_DATETIME_FORMAT' }}</td>
                                    <td>{{ mov.descricao }}</td>
                                    <td>{{ mov.natureza }}</td>
                                    <td class="text-center" data-id="{{ mov.tipo }}">
                                        {% if mov.tipo == mov.TipoMovimentacao.ENTRADA %}
                                            <span class="badge border border-success text-success">Entrada</span></td>
                                        {% else %}
                                            <span class="badge border border-danger text-danger">Saída</span></td>
                                        {% endif %}
                                    <td data-id="{{ mov.forma_pagamento.id }}">{{ mov.forma_pagamento.nome }}</td>
                                    <td>R$ {{ mov.valor }}</td>
                                    <td class="text-center">
                                        {% if object.status %}
                                            <a href="javascript:void(0);" id="edit_{{ mov.id }}" class="btn btn-sm btn-primary mr-2 edit_mov" title="Editar Movimentação" data-id="{{ mov.id }}" data-url="{% url 'movimentacoes:movimentacao_edit' mov.id %}">
                                                            <i class="fas fa-edit "></i>
                                            </a>
                                            <a href="javascript:void(0);" id="delete_{{ mov.id }}" class="btn btn-sm btn-danger mr-2 delete_mov" title="Excluir Movimentação"data-id="{{ mov.id }}" data-url="{% url 'movimentacoes:movimentacao_delete' mov.id %}">
                                                <i class="fas fa-times "></i>
                                            </a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% csrf_token %}
{% endblock content %}


{% block javascript %}

<script src="{% static 'js/datagrid/datatables/datatables.bundle.js' %}"></script>
<script src="{% static 'js/datagrid/datatables/alt-string.js' %}"></script>
<script src="{% static 'js/notifications/toastr/toastr.js' %}"></script>
<script src="{% static 'js/formplugins/select2/select2.bundle.js' %}"></script>
<script src="{% static 'js/siga/movimentacoes/caixas/caixa_detail.js' %}"></script>

{% endblock javascript %}

movimentacoes/templates/movimentacoes/caixas/list.html
{% extends 'base.html' %}
{% load static %}
{% load filters %}


{% block css %}
    <link rel="stylesheet" media="screen, print" href="{% static 'css/datagrid/datatables/datatables.bundle.css' %}">
    <link rel="stylesheet" media="screen, print" href="{% static 'css/notifications/toastr/toastr.css' %}">
{% endblock css %}


{% block nav_inicio %}

<li>

{% endblock nav_inicio %}


{% block nav_financeiro %}

<li class="active open">

{% endblock nav_financeiro %}


{% block nav_financeiro_caixa_historico %}

<li class="active">

{% endblock nav_financeiro_caixa_historico %}


{% block breadcrumb-item %}

<li class="breadcrumb-item activate">Financeiro</li>
<li class="breadcrumb-item activate">Caixas</li>
<li class="breadcrumb-item activate">Histórico</li>

{% endblock breadcrumb-item %}
    

{% block subheader_title %}

    <i class='subheader-icon fal fa-chart-bar'></i> Caixas

{% endblock subheader_title %}

{% block subheader_subtitle %}

    Histórico de Movimentações dos Caixas

{% endblock subheader_subtitle %}


{% block subheader_block %}
    

{% endblock subheader_block %}
    
    
{% block content %}

{% if not caixa_aberto and perms.movimentacoes.add_caixa %}
    
<div class="row">
    <div class="col-xl-12">
        <a href="javascript:void(0)" data-url="{% url 'movimentacoes:caixa_abrir' %}" class="btn btn-success font-weight-bold fs-xl" id="caixa_abrir">
            <i class="fas fa-plus"></i>
            <span class="hidden-md-down"> Abrir Caixa</span>
        </a>
    </div>
</div>

{% endif %}
<div class="row">&nbsp;</div>
<div class="row">
    <div class="col-xl-12">
        <div id="panel-1" class="panel">
            <div class="panel-hdr">
                <h2>
                    Histórico de Caixas
                </h2>
            </div>
            <div class="panel-container show">
                <div class="panel-content">
                    <table id="dt-basic-example" class="table table-bordered table-hover table-striped w-100">
                        <thead class="text-center">
                            <tr>
                                <th>Situação</th>
                                <th>Data</th>
                                <th>Abertura</th>
                                <th>Fechamento</th>
                                <th>Saldo Inicial</th>
                                <th>Saldo</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if object_list %} 
                                {% for caixa in object_list %}
                                    <tr>
                                        <td class="text-center">
                                            
                                            {% if caixa.status %}
                                                <span class="badge badge-success">Aberto</span>
                                            {% else %}
                                                <span class="badge badge-warning">Fechado</span>
                                            {% endif %}
                                                
                                        </td>
                                        <td class="text-center" data-sort="{{ caixa.data|date:'d/m/Y' }}" >{{ caixa.data }}</td>
                                        <td class="text-center">
                                            {{ caixa.abertura }}
                                        </td>
                                        <td class="text-center">
                                            {{ caixa.fechamento|default_if_none:"---" }}
                                        </td>
                                        <td class="text-center">
                                            {{ caixa.saldo_inicial|default_if_none:"0,00" }}
                                        </td>
                                        </td>
                                        <td class="text-center">
                                            {{ caixa.saldo|default_if_none:"0,00" }}
                                        </td>
                                        
                                        <td>
                                            <div class="text-center">
                                                <a href="{% url 'movimentacoes:caixa_detail' caixa.id %}" class="btn btn-sm btn-success mr-2 edit_fpgto" title="Detalhes">
                                                    <i class="fas fa-eye "></i> 
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<form id="form_del_fpgto" method="post">
    {% csrf_token %}
</form>
{% endblock content %}


{% block javascript %}
    <script src="{% static 'js/datagrid/datatables/datatables.bundle.js' %}"></script>
    <script src="{% static 'js/datagrid/datatables/alt-string.js' %}"></script>
    <script src="{% static 'js/notifications/toastr/toastr.js' %}"></script>
    <script src="{% static 'js/siga/movimentacoes/caixas/caixa_list.js' %}"></script>

    <script>
        
    </script>
{% endblock javascript %}
    